### ISSUE TITLE
Found some typos 

### ISSUE THREAD

**Issue by noisytoken** [luisguiserrano/manning#2]
Hi

I've found some typos in your book:

On Pg 50, you have writren:

>Case 3: If the price of the house is lower than the price the model predicted, and the number
of rooms is positive:
• Add 1 cent to the price per room
• Subtract 1 cent to the base price.

However, in case 3, the number of rooms is negative.

For context, take a look at this image https://imgur.com/a/NT5szwl

**Comment by luisguiserrano** [comment]
Thank you so much, noisytoken! Fixed (will come out in the next update).
