### ISSUE TITLE
Ensemble Chapter : sklearn.externals.six

### ISSUE THREAD

**Issue by bvoisine** [luisguiserrano/manning#3]
Was going through the code in the Ensemble chapter. 

It appears sklearn externals six is going to be deprecated and eventually removed.  Recommend installing "six" : https://pypi.org/project/six/   and the code will change from: 
_from sklearn.externals.six import StringIO_  
to:
_from six import StringIO_

**Comment by luisguiserrano** [comment]
Thank you for letting me know, bvoisine! I'll add a comment so people have both options.

**Comment by bvoisine** [comment]
That would be awesome, thank you!  Please let me know if there is anything I can do to help with your book.
